language: node_js
before_script:
- bower install
- gem install scss-lint
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: tools@sap.com
  password:
    secure: Tllia1unc2B1FdhO2FWC/7cHbQEbE1T8jcYWqXeyIljTXK/ExOBRSC3qc2ybrLa8J3T6a4wgVEkAcKXiTOcr5GtCu2DHcF8F/XsMPt/RROxWRl9MrPDSWTEJ1dgwq/rO0jAyl3TlCDctsK5MX7fStuVWkgAcZbNUlMnbJryU7GE=
  organization: GithubTeam
  space: applications
  on:
    repo: reviewninja/dashboard
